name: "Style check"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: phpcs
        run: composer run phpcs

      - name: phpstan
        run: composer run phpstan

      - name: phpmd
        run: composer run phpmd
